# Generated by Django 4.2.4 on 2023-08-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_project_author_issue"),
        ("user", "0002_contributor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributes_to",
                to="project.project",
            ),
        ),
    ]
